CREATE TABLE [dbo].[Table]
(
	[Week] INT NOT NULL PRIMARY KEY, 
    [r_inc_d] INT NULL, 
    [r_av] INT NULL, 
    [r_inc_o] INT NULL, 
    [r_bo] INT NULL, 
    [r_in] INT NULL, 
    [r_cost] INT NULL, 
    [r_order] INT NULL, 
    [r_del] INT NULL, 
    [w_inc_d] INT NULL, 
    [w_av] INT NULL, 
    [w_inc_o] INT NULL, 
    [w_bo] INT NULL, 
    [w_in] INT NULL, 
    [w_cost] INT NULL, 
    [w_order] INT NULL, 
    [w_del] INT NULL, 
    [d_inc_d] INT NULL, 
    [d_av] INT NULL, 
    [d_inc_o] INT NULL, 
    [d_bo] INT NULL, 
    [d_in] INT NULL, 
    [d_cost] INT NULL, 
    [d_order] INT NULL, 
    [d_del] INT NULL, 
    [f_inc_d] INT NULL, 
    [f_av] INT NULL, 
    [f_inc_o] INT NULL, 
    [f_bo] INT NULL, 
    [f_in] INT NULL, 
    [f_cost] INT NULL, 
    [f_order] INT NULL, 
    [f_del] INT NULL
)
